BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "users" (
	"session_id"	TEXT,
	"no_correct_answers"	INTEGER,
	"category"	TEXT
);
CREATE TABLE IF NOT EXISTS "list_answered_questions" (
	"session_id"	TEXT,
	"index_answered_question"	INTEGER
);
CREATE TABLE IF NOT EXISTS "questions" (
	"id"	INTEGER,
	"question"	TEXT,
	"answer1"	TEXT,
	"answer2"	TEXT,
	"answer3"	TEXT,
	"correct_answer"	TEXT,
	"category"	TEXT,
	"image"	TEXT
);
INSERT INTO "questions" VALUES (0,'This flower is a genus of monocotyledonous flowering plants that includes hundreds of species, including the cultivated onion, garlic, scallion, shallot, leek, and chives. The generic name is a Latin word for garlic.','Allium','Rose','Agapanthus','Allium','Flowers','allium_harry-grout-67I-shlEBLY-unsplash.jpg');
INSERT INTO "questions" VALUES (1,'Their garden hybrids have been popular among gardeners since 1862, more hybrid cultivars are being produced constantly. They are mainly of Chinese and Japanese origin. Some species are known as traveller''s joy, a name invented for the sole British native by the herbalist John Gerard, virgin''s bower or old man''s beard, applied to several with prominent seedheads, leather flower for those with fleshy petals or vase vine.','Hemerocallis','Paeonia','Clematis','Clematis','Flowers','clematis_dusan-smetana-haCOsgRt0vo-unsplash.jpg');
INSERT INTO "questions" VALUES (2,'It is a genus of 70–75 species of flowering plants native to Asia and the Americas. By far the greatest species diversity is in eastern Asia, notably Korea, China, and Japan. Most are shrubs 1 to 3 meters tall, but some are small trees, and others lianas reaching up to 30 m (98 ft) by climbing up trees. They can be either deciduous or evergreen, though the widely cultivated temperate species are all deciduous','Hydrangea','Lantana','Kalmia','Hydrangea','Flowers','hortensia_lucie-goncalves-RWcsCAKUMDA-unsplash.jpg');
INSERT INTO "questions" VALUES (3,'It is a genus of 67 species of perennial and annual plants in the family Polemoniaceae. They are found mostly in North America (one in Siberia) in diverse habitats from alpine tundra to open woodland and prairie. Some flower in spring, others in summer and fall. Flowers may be pale blue, violet, pink, bright red, or white. Many are fragrant.','Primula','Phlox','Lupinus','Phlox','Flowers','phlox_pawel-czerwinski-vtKm2M7hmIg-unsplash.jpg');
INSERT INTO "questions" VALUES (4,'It is a genus of flowering plants in the family Theaceae. They are found in eastern and southern Asia, from the Himalayas east to Japan and Indonesia. There are 100–300 described species, with some controversy over the exact number. The genus was named by Linnaeus after the Jesuit botanist, who worked in the Philippines. They are famous throughout East Asia, they are known as cháhuā (茶花, ''tea flower'') in Chinese, tsubaki (椿) in Japanese, dongbaek-kkot (동백꽃) in Korean, and as hoa trà or hoa chè in Vietnamese.','Clerodendrum','Hibiscus','Camellia','Camellia','Flowers','camelia_masaaki-komori-Q9lfbx-_Boc-unsplash.jpg');
INSERT INTO "questions" VALUES (5,'It is a genus of 1,024 species of woody plants in the heath family (Ericaceae), either evergreen or deciduous, and found mainly in Asia, although it is also widespread throughout the lowland and montane forests of the Pacific Northwest, California, and the highlands of the Appalachian Mountains of North America. It is the national flower of Nepal, as well as, the state flower of Washington and West Virginia in United States, the provincial flower of Jiangxi in China and the state tree of Sikkim and Uttarakhand in India. Most species have brightly colored flowers which bloom from late winter through to early summer.','Rhododendron','Oleander','Myrtus','Rhododendron','Flowers','rhododendron_kelly-sikkema-kBDfwG3STjc-unsplash.jpg');
INSERT INTO "questions" VALUES (6,'It is a genus of 260–300 species of flowering plants with showy flowers. It takes its name from the Greek word for a rainbow, which is also the name for the Greek goddess of the rainbow. Some authors state that the name refers to the wide variety of flower colors found among the many species. A common name for some species is ''flags'', while the plants of the subgenus Scorpiris are widely known as ''junos'', particularly in horticulture. It is a popular garden flower.','Lilium','Liatris','Iris','Iris','Flowers','iris_joe-cox-sjzsjGjlcXY-unsplash.jpg');
INSERT INTO "questions" VALUES (7,'It is a genus of about 1000 species of flowering plants, the largest genus of the arum family, Araceae. General common names include tailflower, flamingo flower and laceleaf. The genus is native to the Americas, where it is distributed from northern Mexico to northern Argentina and parts of the Caribbean.','Aster','Anthurium','Alcea','Anthurium','Flowers','anthurium_liam-read-HbTDVIJsM-E-unsplash.jpg');
INSERT INTO "questions" VALUES (8,'It is a genus of bushy, tuberous, herbaceous perennial plants native to Mexico and Central America. A member of the Asteraceae family of dicotyledonous plants, its garden relatives thus include the sunflower, daisy, chrysanthemum, and zinnia. There are 42 species, with hybrids commonly grown as garden plants. Flower forms are variable, with one head per stem, these can be as small as 5 cm diameter or up to 30 cm (1 ft). It was declared the national flower of Mexico in 1963.','Dahlia','Felicia','Delosperma','Dahlia','Flowers','dahlia_severin-stalder-wYUuztU_3Mk-unsplash.jpg');
INSERT INTO "questions" VALUES (9,'It is a genus of about 20 species of herbaceous perennials, shrubs, and biennials commonly called foxgloves. This genus is native to western and southwestern Europe, western and central Asia and northwestern Africa. The flowers are produced on a tall spike, are tubular, and vary in colour with species, from purple to pink, white, and yellow. The scientific name means ''finger-like'' and refers to the ease with which a flower can be fitted over a human fingertip.','Myrtus','Dracula','Digitalis','Digitalis','Flowers','digitalis_clint-mckoy-5gJKQhkzO2g-unsplash.jpg');
INSERT INTO "questions" VALUES (10,'Members of this family are found worldwide, except for Australia, New Guinea, New Zealand, Madagascar, and the extreme polar regions. Most species live in forests or woodland habitats, although a few species are known that live in treeless areas, such as rocky hillsides and deserts. Members of this family are chiefly known for their characteristic behaviour. They mostly forage for insect prey on the trunks and branches of trees, and often communicate by drumming with their beak, producing a reverberatory sound that can be heard at some distance.','Wryneck','Piculet','Woodpecker','Woodpecker','Birds','woodpecker_bruce-jastrow-3FcIYSjtiKU-unsplash.jpg');
INSERT INTO "questions" VALUES (11,'They are generally medium-sized slender birds. Most species live in trees, though a sizeable minority are ground-dwelling. The family has a cosmopolitan distribution, with the majority of species being tropical. Some species are migratory. They feed on insects, insect larvae and a variety of other animals, as well as fruit. Some species are brood parasites, laying their eggs in the nests of other species, but the majority of species raise their own young.','Pidgeon','Cuckoo','Sparrow','Cuckoo','Birds','cuckoo_david-clode-4RA3L2O9XKI-unsplash.jpg');
INSERT INTO "questions" VALUES (12,'They are a family of small to medium-sized, brightly colored birds. Most species have bright plumage with only small differences between the sexes. They consume a wide range of prey usually caught by swooping down from a perch. While they are usually thought to live near rivers and eat fish, many species live away from water and eat small invertebrates. Like other members of their order, they nest in cavities, usually tunnels dug into the natural or artificial banks in the ground.','Kingfisher','Bee-eater','Finch','Kingfisher','Birds','kingfisher_boris-smokrovic-T_diWdiLbg0-unsplash.jpg');
INSERT INTO "questions" VALUES (13,'They are native to the Arctic regions of both North America and the Palearctic, breeding mostly on the tundra. It has a number of unique adaptations to its habitat and lifestyle, which are quite distinct from other extant owls. Most owls sleep during the day and hunt at night, but the this owl is often active during the day, especially in the summertime. They are nomadic birds, rarely breeding at the same locations or with the same mates on an annual basis and often not breeding at all if prey is unavailable.','Tawny Owl','Snowy Owl','Eastern Barn Owl','Snowy Owl','Birds','snowy_owl_jongsun-lee-6l6v9acCX5U-unsplash.jpg');
INSERT INTO "questions" VALUES (14,'This owl shows a partiality for semi-open habitats, particularly woodland edge, as they prefer to roost and nest within dense stands of wood but prefer to hunt over open ground. It is a somewhat specialized predator, focusing its diet almost entirely on small rodents, especially voles, which quite often compose most of their diet. All owls do not build their own nests. These owls generally utilizes nests that are built by other animals.','Long-Eared Owl','Tawny Owl','Short-Eared Owl','Long-Eared Owl','Birds','long_eared_owl_zdenek-machacek-DzXiOcvR1j4-unsplash.jpg');
INSERT INTO "questions" VALUES (15,'It is a small insectivorous passerine bird that belongs to the chat subfamily of the Old World flycatcher family. It was described by Carl Linnaeus in 1758 in the 10th edition of his Systema Naturae. About 12.5–14.0 cm in length, the male and female are similar in colouration, with an orange breast and face lined with grey, brown upper-parts and a whitish belly. It is found across Europe, east to Western Siberia and south to North Africa; it is sedentary in most of its range except the far north.','Robin','Bee-eater','Goldfinch','Robin','Birds','robin_chris-GpNY342iFj4-unsplash.jpg');
INSERT INTO "questions" VALUES (16,'It is a small passerine bird that is native to Europe, North Africa and western and central Asia. It has been introduced to other areas, including Australia, New Zealand and Uruguay. It is often depicted in Italian renaissance paintings of the Madonna and Child. The sexes are broadly similar, with a red face, black and white head, warm brown upper parts, white underparts with buff flanks and breast patches, and black and yellow wings.','Greenfinch','Robin','Goldfinch','Goldfinch','Birds','goldfinch_steve-harrris-gjTk9N8hYME-unsplash.jpg');
INSERT INTO "questions" VALUES (17,'They are long-legged freshwater and coastal birds in the family Ardeidae, with 64 recognised species, some of which are referred to as egrets or bitterns. They are also one of the bird groups that have powder down. Some members of this group nest colonially in trees, while others, notably the bitterns, use reed beds. They are medium- to large-sized birds with long legs and necks. The necks are able to kink in an S-shape, due to the modified shape of the cervical vertebrae, of which they have 20–21. The neck is able to retract and extend and is retracted during flight, unlike most other long-necked birds. ','Heron','Ibis','Stork','Heron','Birds','heron_anchor-lee-e7vV4zPdRFw-unsplash.jpg');
INSERT INTO "questions" VALUES (18,'The adult male, which is found throughout most of Europe, is all black except for a yellow eye-ring and bill and has a rich, melodious song; the adult female and juvenile have mainly dark brown plumage. This species breeds in woods and gardens, building a neat, mud-lined, cup-shaped nest. It is omnivorous, eating a wide range of insects, earthworms, berries, and fruits.','Thrush','Blackbird','Sparrow','Blackbird','Birds','blackbird_heye-jensen-CX0z488nxbc-unsplash.jpg');
INSERT INTO "questions" VALUES (19,'They are characterised by large heads, short tails, and powerful bills and feet, they advertise their territory using loud, simple songs. Most species exhibit grey or bluish upperparts and a black eye stripe. They are omnivorous, eating mostly insects, nuts, and seeds. They forage for insects hidden in or under bark by climbing along tree trunks and branches, sometimes upside-down.','Hawfinch','Nuthatch','Thrush','Nuthatch','Birds','nuthatch_simerpreet-cheema-CBdztXHNTZc-unsplash.jpg');
INSERT INTO "questions" VALUES (20,'Also known as the red admirable, is a well-characterized, medium-sized butterfly with black wings, red bands, and white spots. It has a wingspan of about 2 inches (5 cm). It was first described by Carl Linnaeus in his 1758 10th edition of Systema Naturae. The red admiral is widely distributed across temperate regions of North Africa, the Americas, Europe, Asia, and the Caribbean. It resides in warmer areas, but migrates north in spring and sometimes again in autumn. Typically found in moist woodlands, the red admiral caterpillar''s primary host plant is the stinging nettle','Aglais urticae','Vanessa atalanta','Vanessa cardui','Vanessa atalanta','Butterflies','vanessa_atalanta_vincent-van-zalinge-NbV2zFTlc78-unsplash.jpg');
INSERT INTO "questions" VALUES (21,'More commonly known simply as the peacock butterfly, is a colourful butterfly, found in Europe and temperate Asia as far east as Japan. It was formerly classified as the only member of the genus Inachis (the name is derived from Greek mythology, meaning Io, the daughter of Inachus). The peacock butterfly is resident in much of its range, often wintering in buildings or trees. It therefore often appears quite early in spring. The peacock butterfly has figured in research in which the role of eyespots as an anti-predator mechanism has been investigated. ','Aglais io','Aglais urticae','Kaniska canace','Aglais io','Butterflies','Aglais_io_carolien-van-oijen-WYlm4dfih9g-unsplash.jpg');
INSERT INTO "questions" VALUES (22,'The Old World swallowtail, is a butterfly of the family Papilionidae. The butterfly is also known as the common yellow swallowtail or simply the swallowtail (a common name applied to all members of the family, but this species was the first to be given the name). It is the type species of the genus Papilio. This widespread species is found in much of the Palearctic (it is the only swallowtail in most of Europe) and in North America.','Papilio machalon','Papilio indra','Papilio joanae','Papilio machalon','Butterflies','papilio_machalon_joshua-j-cotten-UmQFndGSHNM-unsplash (1).jpg');
INSERT INTO "questions" VALUES (23,'The common blue butterfly is a butterfly in the family Lycaenidae and subfamily Polyommatinae. The butterfly is found throughout the Palearctic. Butterflies in the Polyommatinae are collectively called blues, from the coloring of the wings. Common blue males usually have wings that are blue above with a black-brown border and a white fringe. The females are usually brown above with a blue dusting and orange spots.','Polyommatus fuchsi','Polyommatus omelkoi','Polyommatus icarus','Polyommatus icarus','Butterflies','polyommatus_ikarus_rzysztof-niewolny-4ioKdP9-3zk-unsplash.jpg');
INSERT INTO "questions" VALUES (24,'It is a small- to medium-sized butterfly species of the whites-and-yellows family Pieridae. It is known in Europe as the small white, in North America as the cabbage white or cabbage butterfly, on several continents as the small cabbage white, and in New Zealand simply as the white butterfly. The butterfly is recognizable by its white color with small black dots on its wings. It is widespread in Europe and Asia, over the past two centuries, it has also spread to North Africa, North America, New Zealand, and Australia, as a result of accidental introductions.','Pieris rapae','Colias eurytheme','Pieris brasicae','Pieris rapae','Butterflies','pieris_rapae_krzysztof-niewolny-VEFpkg6PXn4-unsplash.jpg');
COMMIT;
